url: "https://p3d2.github.io"
baseurl: "/lacemaker"
remote_theme: "mmistakes/minimal-mistakes"

header:
  logo: /assets/images/logo.png

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Optional: Configure theme settings
minimal_mistakes_skin: "dark" # You can change the skin color
logo: "{{ '/assets/images/logo.png' | relative_url }}"

# Navigation links
nav:
  - title: "Home"
    url: "{{ '/' | relative_url }}"
  - title: "Patterns"
    url: "{{ '/patterns/' | relative_url }}"
  - title: "About"
    url: "{{ '/about/' | relative_url }}"

# Pattern collections
collections:
  patterns:
    output: true
    permalink: /patterns/:name/

# Author information
author:
  name: "Pedro E. S. Silva"
  avatar: "/assets/images/avatar.png"
  bio: "A brief bio about me."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/p3d2"