remote_theme: "mmistakes/minimal-mistakes"

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - "assets/react-app"
  - "assets/react-app/*"

include:
  - "_pages"

# Optional: Configure theme settings
name: "Pedro Silva"
url: "https://p3d2.github.io"
title: "Lacemaker"
baseurl: "/lacemaker"
minimal_mistakes_skin: "dirt" # You can change the skin color
logo: /assets/images/logo.png

author:
  name: Pedro Silva

# Pattern collections
collections:
  patterns:
    output: true
    permalink: /patterns/:name/
    layout: single

sidebar:
  nav:
    - docs

# Author information
author:
  name: "Pedro E. S. Silva"
  avatar: "/assets/images/avatar.png"
  bio: "A brief bio about me."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/p3d2"

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      navigation:
        enabled: true
        nav_menu: "main"
      sidebar:
        nav: "docs"
  - scope:
      path: "_patterns"
      type: "patterns"
    values:
      layout: "single"
      navigation:
        enabled: true
        nav_menu: "main"
      sidebar:
        nav: "docs"
  - scope:
      path: "_create"
      type: "create"
    values:
      layout: "single"
      navigation:
        enabled: true
        nav_menu: "main"
