name: conda-lacemaker
channels:
  - https://conda.ovito.org
  - conda-forge
dependencies:
  - ovito=3.10.4
  - numpy
  - scipy=1.13.0
  - pillow=10.3.0
  - wand=0.6.10
  - matplotlib=3.8.4
  - kdepy=1.1.9