name: Update Manifest
on:
  push:
    paths:
      - 'input/json_patterns/*.json'
  
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Manifest
        working-directory: ./assets
        run: node generateManifest.js

      - name: Commit and push changes
        run: |
           git config --global user.name "p3d2"
           git config --global user.email "pess@ua.pt"
           git add input/index.json
           if ! git diff --cached --quiet; then
             git commit -m "Update manifest file"
             git pull --rebase
             git push
           fi
