name: Update Manifest
on:
  push:
    paths:
      - 'input/json_patterns/*.json'
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate Manifest
        working-directory: ./assets
        run: node generateManifest.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ../input/index.json
          git diff --cached --quiet || git commit -m "Update manifest file"
          git push
